/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.repository;
import com.ghailene.portail.entity.OffreService;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface OffreServiceRepository  extends JpaRepository<OffreService, Long> {

	@Query("select offreService from OffreService offreService")
	Page<OffreService> findByPage(Pageable pageable);
	
	@Query(value = "select * from sc_portail.offre_service o where o.type_id = :typeId" , nativeQuery = true)
	public List<OffreService> getTypeById(@Param("typeId") Long typeId); 
	
}