/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.entity;
import java.io.Serializable;
import java.util.List;
import javax.persistence.*;


@Entity
@Table(name="action", schema="scPortail" )
public class Action implements Serializable {

	private static final long serialVersionUID = 1L;

    //Entity primary key
    @Id
    @Column(name="action_id", nullable=false)
    private Long actionId ;
  
	 // Entity data fields
    @Column(name="type_name", nullable=false)
    private String typeName ;
    @Column(name="name", length=2147483647)
    private String name ;

 
    // Entity links


    @OneToMany(mappedBy="action", targetEntity=Commande.class)
    private List<Commande> listOfCommande;



    // Constructor

	public Action() {	
		super();
	}

    // Getter and setter

    public void setActionId( Long actionId ) {
        this.actionId = actionId ;
    }
    public Long getActionId() {
        return this.actionId ;
    }


	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public void setName(String name) {
		this.name = name ;
	}
	public String getName() {
		return this.name ;
	}

    public void setListOfCommande( List<Commande> listOfCommande ) {
        this.listOfCommande = listOfCommande ;
    }
    public List<Commande> getListOfCommande() {
        return this.listOfCommande ;
    }



}

