/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.entity;
import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;


@Entity
@Table(name="commande", schema="scPortail" )
public class Commande implements Serializable {

	private static final long serialVersionUID = 1L;

    //Entity primary key
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY,generator="MySequenceGenerator")
    @SequenceGenerator(allocationSize=1, schema="scPortail",  name="MySequenceGenerator", sequenceName = "portail_id_seq")
    @Column(name="commande_id", nullable=false)
    private Long commandeId ;
  
	 // Entity data fields
    @Column(name="name", nullable=false, length=2147483647)
    private String name ;
    @Column(name="description", length=2147483647)
    private String description ;
    @Column(name="status", length=2147483647)
    private String status ;

 
    // Entity links

    @JsonIgnore
    @OneToMany(mappedBy="commande", targetEntity=HistoriqueCommande.class)
    private List<HistoriqueCommande> listOfHistoriqueCommande;


    @JsonIgnore
    @OneToMany(mappedBy="commande", targetEntity=Panier.class)
    private List<Panier> listOfPanier;


    @JsonIgnore
    @OneToMany(mappedBy="commande", targetEntity=Alerts.class)
    private List<Alerts> listOfAlerts;


    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="action_id", referencedColumnName="action_id")
    private Action action      ;


    @JsonIgnore
    @ManyToOne
    @JoinColumn(name="service_id", referencedColumnName="service_id")
    private OffreService offreService;



    // Constructor

	public Commande() {	
		super();
	}

    // Getter and setter

    public void setCommandeId( Long commandeId ) {
        this.commandeId = commandeId ;
    }
    public Long getCommandeId() {
        return this.commandeId ;
    }

	public void setName(String name) {
		this.name = name ;
	}
	public String getName() {
		return this.name ;
	}
	public void setDescription(String description) {
		this.description = description ;
	}
	public String getDescription() {
		return this.description ;
	}
	public void setStatus(String status) {
		this.status = status ;
	}
	public String getStatus() {
		return this.status ;
	}

    public void setListOfHistoriqueCommande( List<HistoriqueCommande> listOfHistoriqueCommande ) {
        this.listOfHistoriqueCommande = listOfHistoriqueCommande ;
    }
    public List<HistoriqueCommande> getListOfHistoriqueCommande() {
        return this.listOfHistoriqueCommande ;
    }

    public void setListOfPanier( List<Panier> listOfPanier ) {
        this.listOfPanier = listOfPanier ;
    }
    public List<Panier> getListOfPanier() {
        return this.listOfPanier ;
    }

    public void setListOfAlerts( List<Alerts> listOfAlerts ) {
        this.listOfAlerts = listOfAlerts ;
    }
    public List<Alerts> getListOfAlerts() {
        return this.listOfAlerts ;
    }

    public void setAction( Action action       ) {
        this.action       = action       ;
    }
    public Action getAction() {
        return this.action       ;
    }

    public void setOffreService( OffreService offreService ) {
        this.offreService = offreService ;
    }
    public OffreService getOffreService() {
        return this.offreService ;
    }



}

