/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.entity;
import java.io.Serializable;
import java.util.Date;

import javax.persistence.*;


@Entity
@Table(name="news", schema="scPortail" )
public class News implements Serializable {

	private static final long serialVersionUID = 1L;

    //Entity primary key
    @Id
    @Column(name="news_id", nullable=false)
    private Long newsId ;
  
	 // Entity data fields
    @Column(name="description", length=2147483647)
    private String description ;
    
    @Column(name="newsDate")
    private Date newsDate ;
    
 
    // Entity links


    public Date getNewsDate() {
		return newsDate;
	}

	public void setNewsDate(Date newsDate) {
		this.newsDate = newsDate;
	}
	@ManyToOne
    @JoinColumn(name="service_id", referencedColumnName="service_id")
    private OffreService offreService;



    // Constructor

	public News() {	
		super();
	}

    // Getter and setter

    public void setNewsId( Long newsId ) {
        this.newsId = newsId ;
    }
    public Long getNewsId() {
        return this.newsId ;
    }

	public void setDescription(String description) {
		this.description = description ;
	}
	public String getDescription() {
		return this.description ;
	}

    public void setOffreService( OffreService offreService ) {
        this.offreService = offreService ;
    }
    public OffreService getOffreService() {
        return this.offreService ;
    }



}

