/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.entity;
import java.io.Serializable;
import javax.persistence.*;


@Entity
@Table(name="panier", schema="scPortail" )
public class Panier implements Serializable {

	private static final long serialVersionUID = 1L;

    //Entity primary key
    @Id
    @Column(name="panier_id", nullable=false)
    private Long panierId ;
  
	 // Entity data fields
    @Column(name="name", length=2147483647)
    private String name ;

 
    // Entity links


    @ManyToOne
    @JoinColumn(name="commande_id", referencedColumnName="commande_id")
    private Commande commande    ;



    // Constructor

	public Panier() {	
		super();
	}

    // Getter and setter

    public void setPanierId( Long panierId ) {
        this.panierId = panierId ;
    }
    public Long getPanierId() {
        return this.panierId ;
    }

	public void setName(String name) {
		this.name = name ;
	}
	public String getName() {
		return this.name ;
	}

    public void setCommande( Commande commande     ) {
        this.commande     = commande     ;
    }
    public Commande getCommande() {
        return this.commande     ;
    }



}

