/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.entity;
import java.io.Serializable;
import javax.persistence.*;


@Entity
@Table(name="reports", schema="scPortail" )
public class Reports implements Serializable {

	private static final long serialVersionUID = 1L;

    //Entity primary key
    @Id
    @Column(name="report_id", nullable=false)
    private Long reportId ;
  
	 // Entity data fields
    @Column(name="name", length=2147483647)
    private String name ;

 
    // Entity links


    @ManyToOne
    @JoinColumn(name="service_id", referencedColumnName="service_id")
    private OffreService offreService;



    // Constructor

	public Reports() {	
		super();
	}

    // Getter and setter

    public void setReportId( Long reportId ) {
        this.reportId = reportId ;
    }
    public Long getReportId() {
        return this.reportId ;
    }

	public void setName(String name) {
		this.name = name ;
	}
	public String getName() {
		return this.name ;
	}

    public void setOffreService( OffreService offreService ) {
        this.offreService = offreService ;
    }
    public OffreService getOffreService() {
        return this.offreService ;
    }



}

