/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service;
import com.ghailene.portail.entity.Action;
import java.util.List;

/**
 * Service interface for Action.
 * 
 */

public interface ActionService {

	public Action findOne(Long actionId);

	public Action add(Action action);

	public Action update(Action action);

	public boolean delete(Long actionId);

	public List<Action> findAll();

	public List<Action>findByPage(int page, int size);

	public long count();

}

	
