/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service;
import com.ghailene.portail.entity.Alerts;
import java.util.List;

/**
 * Service interface for Alerts.
 * 
 */

public interface AlertsService {

	public Alerts findOne(Long alertId);

	public Alerts add(Alerts alerts);

	public Alerts update(Alerts alerts);

	public boolean delete(Long alertId);

	public List<Alerts> findAll();

	public List<Alerts>findByPage(int page, int size);

	public long count();

}

	
