/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service;
import com.ghailene.portail.entity.Commande;
import java.util.List;

/**
 * Service interface for Commande.
 * 
 */

public interface CommandeService {

	public Commande findOne(Long commandeId);

	public Commande add(Commande commande);

	public Commande update(Commande commande);

	public boolean delete(Long commandeId);

	public List<Commande> findAll();

	public List<Commande>findByPage(int page, int size);

	public long count();
	
	public List<Commande>findByStatus(String status);
}

	
