/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service;
import com.ghailene.portail.entity.HistoriqueCommande;
import java.util.List;

/**
 * Service interface for HistoriqueCommande.
 * 
 */

public interface HistoriqueCommandeService {

	public HistoriqueCommande findOne(Long historiqueId);

	public HistoriqueCommande add(HistoriqueCommande historiqueCommande);

	public HistoriqueCommande update(HistoriqueCommande historiqueCommande);

	public boolean delete(Long historiqueId);

	public List<HistoriqueCommande> findAll();

	public List<HistoriqueCommande>findByPage(int page, int size);

	public long count();

}

	
