/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service;
import com.ghailene.portail.entity.News;
import java.util.List;

/**
 * Service interface for News.
 * 
 */

public interface NewsService {

	public News findOne(Long newsId);

	public News add(News news);

	public News update(News news);

	public boolean delete(Long newsId);

	public List<News> findAll();

	public List<News>findByPage(int page, int size);

	public long count();

}

	
