/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service;
import com.ghailene.portail.entity.OffreService;


import java.util.List;

/**
 * Service interface for OffreService.
 * 
 */

public interface OffreServiceService {

	public OffreService findOne(Long serviceId);

	public List<OffreService> getTypeById(Long typeId);
	
	public OffreService add(OffreService offreService);

	public OffreService update(OffreService offreService);

	public boolean delete(Long serviceId);

	public List<OffreService> findAll();

	public List<OffreService>findByPage(int page, int size);

	public long count();
	
	

}

	
