/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service;
import com.ghailene.portail.entity.Reports;
import java.util.List;

/**
 * Service interface for Reports.
 * 
 */

public interface ReportsService {

	public Reports findOne(Long reportId);

	public Reports add(Reports reports);

	public Reports update(Reports reports);

	public boolean delete(Long reportId);

	public List<Reports> findAll();

	public List<Reports>findByPage(int page, int size);

	public long count();

}

	
