/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.dto;

public class ActionDto {
  

	private Long actionId ;
	private String typeName ;
	private String name ;


	public ActionDto (){
	}


	public void setActionId(Long actionId) {
		this.actionId = actionId ;
	}

	public Long getActionId() {
		return this.actionId ;
	}


	


	public String getTypeName() {
		return typeName;
	}


	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}


	public void setName(String name) {
		this.name = name ;
	}

	public String getName() {
		return this.name ;
	}



}