/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.dto;

public class CommandeDto {
  

	private Long commandeId ;
	private String name ;
	private String description ;
	private String status ;

	private ActionDto action       ;
	private OffreServiceDto offreService ;

	public CommandeDto (){
	}


	public void setCommandeId(Long commandeId) {
		this.commandeId = commandeId ;
	}

	public Long getCommandeId() {
		return this.commandeId ;
	}


	public void setName(String name) {
		this.name = name ;
	}

	public String getName() {
		return this.name ;
	}


	public void setDescription(String description) {
		this.description = description ;
	}

	public String getDescription() {
		return this.description ;
	}


	public void setStatus(String status) {
		this.status = status ;
	}

	public String getStatus() {
		return this.status ;
	}



    public void setAction( ActionDto action ) {
        this.action  = action ;
    }
    public ActionDto getAction() {
        return this.action ;
    }

    public void setOffreService( OffreServiceDto offreService ) {
        this.offreService  = offreService ;
    }
    public OffreServiceDto getOffreService() {
        return this.offreService ;
    }

}