/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.dto;

import java.util.Date;

public class NewsDto {
  

	private Long newsId ;
	private String description ;
	private Date newsDate ;
	
	public Date getNewsDate() {
		return newsDate;
	}


	public void setNewsDate(Date newsDate) {
		this.newsDate = newsDate;
	}
	private OffreServiceDto offreService ;

	public NewsDto (){
	}


	public void setNewsId(Long newsId) {
		this.newsId = newsId ;
	}

	public Long getNewsId() {
		return this.newsId ;
	}


	public void setDescription(String description) {
		this.description = description ;
	}

	public String getDescription() {
		return this.description ;
	}



    public void setOffreService( OffreServiceDto offreService ) {
        this.offreService  = offreService ;
    }
    public OffreServiceDto getOffreService() {
        return this.offreService ;
    }

}