/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.dto;

public class PanierDto {
  

	private Long panierId ;
	private String name ;

	private CommandeDto commande     ;

	public PanierDto (){
	}


	public void setPanierId(Long panierId) {
		this.panierId = panierId ;
	}

	public Long getPanierId() {
		return this.panierId ;
	}


	public void setName(String name) {
		this.name = name ;
	}

	public String getName() {
		return this.name ;
	}



    public void setCommande( CommandeDto commande ) {
        this.commande  = commande ;
    }
    public CommandeDto getCommande() {
        return this.commande ;
    }

}