/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.dto;

public class ReportsDto {
  

	private Long reportId ;
	private String name ;

	private OffreServiceDto offreService ;

	public ReportsDto (){
	}


	public void setReportId(Long reportId) {
		this.reportId = reportId ;
	}

	public Long getReportId() {
		return this.reportId ;
	}


	public void setName(String name) {
		this.name = name ;
	}

	public String getName() {
		return this.name ;
	}



    public void setOffreService( OffreServiceDto offreService ) {
        this.offreService  = offreService ;
    }
    public OffreServiceDto getOffreService() {
        return this.offreService ;
    }

}