/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service.impl;
import com.ghailene.portail.entity.Action;
import java.util.List;
import com.ghailene.portail.repository.ActionRepository;
import com.ghailene.portail.service.ActionService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Action.
 * 
 */

@Service
public class ActionServiceImpl implements ActionService {

	@Autowired
	private ActionRepository actionRepository;

	@Override
	public Action findOne(Long actionId){
		
				return actionRepository.findById(actionId).get();
			}

	@Override
	public Action add(Action action){

		return actionRepository.save(action);
	}

	@Override
	public Action update(Action action){

		return actionRepository.save(action);
	}
	
	@Override
	public boolean delete(Long actionId){

				if (actionRepository.findById(actionId) != null) {
			actionRepository.deleteById(actionId);
			return true;
		}
				return false;
	}

	@Override
	public List<Action> findAll(){
		return actionRepository.findAll();
	}

	@Override
	public List<Action> findByPage(int page, int size){
		return actionRepository.findByPage(PageRequest.of(page, size)).getContent();
	}

	@Override
	public long count() {
		return actionRepository.count();
	}
}


