/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service.impl;
import com.ghailene.portail.entity.Alerts;
import java.util.List;
import com.ghailene.portail.repository.AlertsRepository;
import com.ghailene.portail.service.AlertsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Alerts.
 * 
 */

@Service
public class AlertsServiceImpl implements AlertsService {

	@Autowired
	private AlertsRepository alertsRepository;

	@Override
	public Alerts findOne(Long alertId){
		
				return alertsRepository.findById(alertId).get();
			}

	@Override
	public Alerts add(Alerts alerts){

		return alertsRepository.save(alerts);
	}

	@Override
	public Alerts update(Alerts alerts){

		return alertsRepository.save(alerts);
	}
	
	@Override
	public boolean delete(Long alertId){

				if (alertsRepository.findById(alertId) != null) {
			alertsRepository.deleteById(alertId);
			return true;
		}
				return false;
	}

	@Override
	public List<Alerts> findAll(){
		return alertsRepository.findAll();
	}

	@Override
	public List<Alerts> findByPage(int page, int size){
		return alertsRepository.findByPage(PageRequest.of(page, size)).getContent();
	}

	@Override
	public long count() {
		return alertsRepository.count();
	}
}


