/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service.impl;
import com.ghailene.portail.entity.HistoriqueCommande;
import java.util.List;
import com.ghailene.portail.repository.HistoriqueCommandeRepository;
import com.ghailene.portail.service.HistoriqueCommandeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Service implementation for HistoriqueCommande.
 * 
 */

@Service
public class HistoriqueCommandeServiceImpl implements HistoriqueCommandeService {

	@Autowired
	private HistoriqueCommandeRepository historiqueCommandeRepository;

	@Override
	public HistoriqueCommande findOne(Long historiqueId){
		
				return historiqueCommandeRepository.findById(historiqueId).get();
			}

	@Override
	public HistoriqueCommande add(HistoriqueCommande historiqueCommande){

		return historiqueCommandeRepository.save(historiqueCommande);
	}

	@Override
	public HistoriqueCommande update(HistoriqueCommande historiqueCommande){

		return historiqueCommandeRepository.save(historiqueCommande);
	}
	
	@Override
	public boolean delete(Long historiqueId){

				if (historiqueCommandeRepository.findById(historiqueId) != null) {
			historiqueCommandeRepository.deleteById(historiqueId);
			return true;
		}
				return false;
	}

	@Override
	public List<HistoriqueCommande> findAll(){
		return historiqueCommandeRepository.findAll();
	}

	@Override
	public List<HistoriqueCommande> findByPage(int page, int size){
		return historiqueCommandeRepository.findByPage(PageRequest.of(page, size)).getContent();
	}

	@Override
	public long count() {
		return historiqueCommandeRepository.count();
	}
}


