/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:58 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service.impl;
import com.ghailene.portail.entity.News;
import java.util.List;
import com.ghailene.portail.repository.NewsRepository;
import com.ghailene.portail.service.NewsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Service implementation for News.
 * 
 */

@Service
public class NewsServiceImpl implements NewsService {

	@Autowired
	private NewsRepository newsRepository;

	@Override
	public News findOne(Long newsId){
		
				return newsRepository.findById(newsId).get();
			}

	@Override
	public News add(News news){

		return newsRepository.save(news);
	}

	@Override
	public News update(News news){

		return newsRepository.save(news);
	}
	
	@Override
	public boolean delete(Long newsId){

				if (newsRepository.findById(newsId) != null) {
			newsRepository.deleteById(newsId);
			return true;
		}
				return false;
	}

	@Override
	public List<News> findAll(){
		return newsRepository.findAll();
	}

	@Override
	public List<News> findByPage(int page, int size){
		return newsRepository.findByPage(PageRequest.of(page, size)).getContent();
	}

	@Override
	public long count() {
		return newsRepository.count();
	}
}


