/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service.impl;
import com.ghailene.portail.entity.OffreService;
import java.util.List;
import com.ghailene.portail.repository.OffreServiceRepository;
import com.ghailene.portail.service.OffreServiceService;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Service implementation for OffreService.
 * 
 */

@Service
public class OffreServiceServiceImpl implements OffreServiceService {

	@Autowired
	private OffreServiceRepository offreServiceRepository;

	@Override
	public OffreService findOne(Long serviceId){
		
				return offreServiceRepository.findById(serviceId).get();
			}

	@Override
	public OffreService add(OffreService offreService){

		return offreServiceRepository.save(offreService);
	}

	@Override
	public OffreService update(OffreService offreService){

		return offreServiceRepository.save(offreService);
	}
	
	@Override
	public boolean delete(Long serviceId){

				if (offreServiceRepository.findById(serviceId) != null) {
			offreServiceRepository.deleteById(serviceId);
			return true;
		}
				return false;
	}

	@Override
	public List<OffreService> findAll(){
		return offreServiceRepository.findAll();
	}

	@Override
	public List<OffreService> findByPage(int page, int size){
		return offreServiceRepository.findByPage(PageRequest.of(page, size)).getContent();
	}

	@Override
	public long count() {
		return offreServiceRepository.count();
	}
	
	public List<OffreService> getTypeById(Long typeId){
		return offreServiceRepository.getTypeById(typeId);
	}
	
	
}


