/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service.impl;
import com.ghailene.portail.entity.Panier;
import java.util.List;
import com.ghailene.portail.repository.PanierRepository;
import com.ghailene.portail.service.PanierService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Panier.
 * 
 */

@Service
public class PanierServiceImpl implements PanierService {

	@Autowired
	private PanierRepository panierRepository;

	@Override
	public Panier findOne(Long panierId){
		
				return panierRepository.findById(panierId).get();
			}

	@Override
	public Panier add(Panier panier){

		return panierRepository.save(panier);
	}

	@Override
	public Panier update(Panier panier){

		return panierRepository.save(panier);
	}
	
	@Override
	public boolean delete(Long panierId){

				if (panierRepository.findById(panierId) != null) {
			panierRepository.deleteById(panierId);
			return true;
		}
				return false;
	}

	@Override
	public List<Panier> findAll(){
		return panierRepository.findAll();
	}

	@Override
	public List<Panier> findByPage(int page, int size){
		return panierRepository.findByPage(PageRequest.of(page, size)).getContent();
	}

	@Override
	public long count() {
		return panierRepository.count();
	}
}


