/*
 * Created on 2019-10-09 ( Date ISO 2019-10-09 - Time 11:43:59 )
 * Generated by JCharzyGen version 0
*/
package com.ghailene.portail.service.impl;
import com.ghailene.portail.entity.Reports;
import java.util.List;
import com.ghailene.portail.repository.ReportsRepository;
import com.ghailene.portail.service.ReportsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Service implementation for Reports.
 * 
 */

@Service
public class ReportsServiceImpl implements ReportsService {

	@Autowired
	private ReportsRepository reportsRepository;

	@Override
	public Reports findOne(Long reportId){
		
				return reportsRepository.findById(reportId).get();
			}

	@Override
	public Reports add(Reports reports){

		return reportsRepository.save(reports);
	}

	@Override
	public Reports update(Reports reports){

		return reportsRepository.save(reports);
	}
	
	@Override
	public boolean delete(Long reportId){

				if (reportsRepository.findById(reportId) != null) {
			reportsRepository.deleteById(reportId);
			return true;
		}
				return false;
	}

	@Override
	public List<Reports> findAll(){
		return reportsRepository.findAll();
	}

	@Override
	public List<Reports> findByPage(int page, int size){
		return reportsRepository.findByPage(PageRequest.of(page, size)).getContent();
	}

	@Override
	public long count() {
		return reportsRepository.count();
	}
}


